// Generated by gencpp from file gazebo_ros_link_attacher/Detach.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_LINK_ATTACHER_MESSAGE_DETACH_H
#define GAZEBO_ROS_LINK_ATTACHER_MESSAGE_DETACH_H

#include <ros/service_traits.h>


#include <gazebo_ros_link_attacher/DetachRequest.h>
#include <gazebo_ros_link_attacher/DetachResponse.h>


namespace gazebo_ros_link_attacher
{

struct Detach
{

typedef DetachRequest Request;
typedef DetachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detach
} // namespace gazebo_ros_link_attacher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_link_attacher::Detach > {
  static const char* value()
  {
    return "8bb95f98092206e1bde0ffc73ca71b25";
  }

  static const char* value(const ::gazebo_ros_link_attacher::Detach&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_link_attacher::Detach > {
  static const char* value()
  {
    return "gazebo_ros_link_attacher/Detach";
  }

  static const char* value(const ::gazebo_ros_link_attacher::Detach&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_link_attacher::DetachRequest> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::Detach >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::DetachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::Detach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::DetachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::DetachRequest> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::Detach >
template<>
struct DataType< ::gazebo_ros_link_attacher::DetachRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::Detach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::DetachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_link_attacher::DetachResponse> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::Detach >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::DetachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::Detach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::DetachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::DetachResponse> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::Detach >
template<>
struct DataType< ::gazebo_ros_link_attacher::DetachResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::Detach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::DetachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_LINK_ATTACHER_MESSAGE_DETACH_H
