// Generated by gencpp from file gazebo_ros_link_attacher/DetachResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_LINK_ATTACHER_MESSAGE_DETACHRESPONSE_H
#define GAZEBO_ROS_LINK_ATTACHER_MESSAGE_DETACHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_ros_link_attacher
{
template <class ContainerAllocator>
struct DetachResponse_
{
  typedef DetachResponse_<ContainerAllocator> Type;

  DetachResponse_()
    : ok(false)
    , message()  {
    }
  DetachResponse_(const ContainerAllocator& _alloc)
    : ok(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetachResponse_

typedef ::gazebo_ros_link_attacher::DetachResponse_<std::allocator<void> > DetachResponse;

typedef boost::shared_ptr< ::gazebo_ros_link_attacher::DetachResponse > DetachResponsePtr;
typedef boost::shared_ptr< ::gazebo_ros_link_attacher::DetachResponse const> DetachResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator1> & lhs, const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator1> & lhs, const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_ros_link_attacher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6fcb3b1ed8c7743c7fb7d5bcca28513";
  }

  static const char* value(const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6fcb3b1ed8c7743ULL;
  static const uint64_t static_value2 = 0xc7fb7d5bcca28513ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ros_link_attacher/DetachResponse";
  }

  static const char* value(const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"string message\n"
;
  }

  static const char* value(const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetachResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ros_link_attacher::DetachResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_ROS_LINK_ATTACHER_MESSAGE_DETACHRESPONSE_H
