(cl:defpackage gazebo_ros_link_attacher-srv
  (:use )
  (:export
   "ATTACH"
   "<ATTACH-REQUEST>"
   "ATTACH-REQUEST"
   "<ATTACH-RESPONSE>"
   "ATTACH-RESPONSE"
   "DETACH"
   "<DETACH-REQUEST>"
   "DETACH-REQUEST"
   "<DETACH-RESPONSE>"
   "DETACH-RESPONSE"
   "SETSTATIC"
   "<SETSTATIC-REQUEST>"
   "SETSTATIC-REQUEST"
   "<SETSTATIC-RESPONSE>"
   "SETSTATIC-RESPONSE"
  ))

